### ISSUE TITLE
Practice Application: Milestone 2 Documentation

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#137]
### What's up?

Time has come to document what have done so far in practice application. We have distributed the tasks among the team members in meeting [#16](https://github.com/bounswe/bounswe2022group8/wiki/Week-11-Meeting-Notes-16%F0%9F%97%92%EF%B8%8F). Please refer to the Google Documents provided in our Discord channel under the ```milestone-general```.

### To Do

Following actions must be taken:
- [x] Open a Google Documents for the Milestone 2 and prepare subsections. @simsekhebun 
- [ ] Document _summary of project and overall status_. @mumcusena 
- [ ] Provide URL of our deployed application. @ooodogodogodogo 
- [ ] "Update your GitHub wiki page to document the application URL." (Awful English, most probably trying to say that we have to put the link of the deployed application to somewhere in our Wiki) @ooodogodogodogo 
- [ ] Perform user acceptance tests. 
- [x] Describe _basic functionality of your project_. @serdarakol 
- [ ] Contribute individually to the section _–Challenges you met as a group_. @everyone
- [x] List the status of deliverables. @KarahanS 
- [x] Prepare project plan. (@sinemKocoglu, @kostanya, @mumcusena)
- [ ] Brief and clear summary of work performed by each team member (in tabular format). This time, it must be written to Google Docs using hyperlinks. @everyone
- [x] Evaluating the tools and processes we have used to manage our team project. @kostanya 
- [ ] Creating the PDF by merging all necessary stuff. @mumcusena 

### Deadline

_Deadline: 20.05.22 @23.59_

**Comment by KarahanS** [comment]
* Listed the status of deliverables in tabular format. Also prepared _Evaluation of the Status of Deliverables_ section in which I briefly described the content of the deliverable and what we were up to.

**Comment by KarahanS** [comment]
* Contributed to the _Challenges you met as a group_ section.

**Comment by serdarakol** [comment]
basic functionality part of the report is written

**Comment by KarahanS** [comment]
* Added brief summary of what I've done.

**Comment by KarahanS** [comment]
Practice App Implementation is over. No action is taken, closing the issue.
