### ISSUE TITLE
GEN-18: Project Plan Update

### ISSUE THREAD

**Issue by kostanya** [bounswe/bounswe2022group8#170]
### What's up?

In [Week 2 Meeting #2](https://github.com/bounswe/bounswe2022group8/wiki/Week-2-Meeting-%232), we decided to update our project plan for CmpE 451 course. We also decided that it would be better to use GanttProject instead of ProjectLibre as the project management tool.

### To Do

- [ ] Create seperate Project Plan sections for CmpE 352 and CmpE 451 on the homepage. 
- [ ] Find the project plans for CmpE 352 and add them to the relevant page.
- [ ] Create a draft project plan for CmpE 451 based on the project plan we prepared previous year.

### Deadline

16.10.2022 @18.00

### Additional Information

As mentioned in #161, everybody needs to review the former project plan individually, take notes for possible updates/improvements and share them in our discord channel. We need to prepare a proper project plan and start implementation as quickly as possible. 

### Reviewers

@KarahanS

**Comment by KarahanS** [comment]
Thanks for the contributions. Keeping this issue open for now. Waiting for our change/update actions regarding the project planning.
