### ISSUE TITLE
MIL-1: Milestone I Deliverables

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#201]
### What's up?

All Milestone 1 Deliverables except the Milestone Group Review must be completed until 1.11.2022 @12.00 (noon). Please review the [document](https://moodle.boun.edu.tr/pluginfile.php/1137699/mod_resource/content/1/Customer%20Milestone%201%20Deliverables.pdf) in Moodle. It states that this time we should collect our deliverables as ```.md``` files rather than ```.pdf``` file. We should add the hyperlinks of [requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements), [class diagram](https://github.com/bounswe/bounswe2022group8/wiki/Class-Diagram), [use case diagram](https://github.com/bounswe/bounswe2022group8/wiki/Use-case-diagram), [sequence diagram](https://github.com/bounswe/bounswe2022group8/wiki/Sequence-Diagrams), scenarios & mockups [1](https://github.com/bounswe/bounswe2022group8/wiki/Class-Diagram), [2](https://github.com/bounswe/bounswe2022group8/wiki/Scenario-2), [3](https://github.com/bounswe/bounswe2022group8/wiki/Scenario-3), and [project plan](https://github.com/bounswe/bounswe2022group8/wiki/CmpE-451-Project-Plan).

### To Do

- [x] Create a folder named ```CMPE451_Customer_Presentation_Milestone_1``` inside `deliverables`  folder in our repository.
- [x] Deploy the application
- [x] Create a pre-release version of our software that marks this version
>Release Name: 0.1.0-alpha (pre-release option)
Release Description: Brief description w/r to your requirements
Tag name: customer-presentation-1
- [x] All instructions for building must be provided (with docker).
- [x] The following deliverables must be compiled into a single report. We will be providing the hyperlinks:
   - [x] Software Requirements Specification
   - [x] Software Design (UML)
   - [x] Scenarios and Mockups
   - [x] Project Plan
   - [x] Individual Contribution Reports
   - [x] Customer Milestone 1 Group Review
- [x] Each member should add a subsection under the `Individual reports` section. These sections should be sorted alphabetically according to the surnames of team members. Please read this part in detail to what to put in this part.

### Deadline

1.11.2022 @12.00 (noon)

### Additional Information

We have already made the task distributions covering the majority of the tasks listed above. Don't forget to open the related sub-issue and reference this issue. 

### Reviewers

Literally @everyone.

**Comment by KarahanS** [comment]
I created a new branch [feature/MIL](https://github.com/bounswe/bounswe2022group8/tree/feature/MIL) and added some markdown files. Let's collect necessary deliverables in that branch and then merge it to customer when we're done. I'm not sure if we have to collect **everything** to a single markdown file or we can use multiple markdown files but not really important at the moment. If we have to collect them into a single one, we can simply combine the markdown files.

**Comment by KarahanS** [comment]
Added `The requirements addressed in this milestone` section under the **Milestone Group Review**. Please revise carefully and let me know if anything is missing.

**Comment by mustafa-cihan** [comment]
I provided the hyperlinks for  Software Requirements Specification, Software Design (UML), Scenarios and Mockups and Project Plan.

**Comment by KarahanS** [comment]
Milestone I Deliverables are collected and can be found [here](https://github.com/bounswe/bounswe2022group8/blob/master/Deliverables/CMPE451_Customer_Presentation_Milestone_1/Deliverables.md). No further action is required, closing the issue.
