### ISSUE TITLE
MIL-5: Milestone 1 Group Review

### ISSUE THREAD

**Issue by MustafaEmreErengul** [bounswe/bounswe2022group8#226]
### What's up?

In this report, the work we have done so far needs to be reflected. The report should be prepared based on the content of our repository and observations. It will give us an  opportunity to examine the work we have done and the processes & tools we have chosen. Also it is a document for the assessment  & improvement of our project.

### To Do

- [x] Executive Summary: Summary of the project status and any changes that are planned for moving forward.
- [x] List and status of deliverables.
- [x] Evaluation of the status of deliverables and its impact on your project plan.
- [x] Evaluation of tools and processes you have used to manage your team project.
- [x] The requirements addressed in this milestone.
- [x] Overall description of responsibilities that are assigned to each member.
- [x] A Summary of work performed by each team member (in tabular format).

### Deadline

04.11.2022 @22.55

### Additional Information

This report requires the effort of all our group members.

### Reviewers

@KarahanS @MustafaEmreErengul

**Comment by KarahanS** [comment]
All related sub-issues are closed, closing the issue.
