### ISSUE TITLE
MIL-8: Milestone 2 Group Review

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#295]
### What's up?

In this report, the work we have done so far needs to be reflected. The report should be prepared based on the content of our repository and observations. It will give us an  opportunity to examine the work we have done and the processes & tools we have chosen. Also it is a document for the assessment  & improvement of our project.

### To Do

- [x] Executive Summary: Summary of the project status and any changes that are planned for moving forward.  @BElifb 
- [x] List and status of deliverables.  @MustafaEmreErengul 
- [x] Explain the work you have completed towards the application of the W3C standards  @mustafa-cihan @kostanya 
- [x] Evaluation of tools and processes you have used to manage your team project.  @BElifb 
- [x] The requirements addressed in this milestone.  @mumcusena 
- [x] Overall description of responsibilities that are assigned to each member.   @everyone
- [x] A Summary of work performed by each team member (in tabular format).   @everyone
- [x] User interfaces/User experiences for web @sinemKocoglu 
- [x] User interfaces/User experiences for mobile @ooodogodogodogo 
- [x] Annotations @kostanya 

### Deadline

10.12.2022 @16.00

### Additional Information

Please work on the branch [feature/MIL](https://github.com/bounswe/bounswe2022group8/tree/feature/MIL). We'll merge it to `master` after everything is ready to go.

### Reviewers

@KarahanS - Issue will be closed when everything is ready to go.

**Comment by KarahanS** [comment]
Hi @mumcusena, could you please update the assignee information for the tasks? I don't really recall what we assigned to whom.

**Comment by mumcusena** [comment]
Updated the assignees according to our meeting notes.
