### ISSUE TITLE
MIL-11: Milestone 2 Deliverables

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#300]
### What's up?

All Milestone 2 Deliverables except the Milestone Group Review must be completed until 6.12.2022 - 23:55. We should add the hyperlinks of [requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements), [class diagram](https://github.com/bounswe/bounswe2022group8/wiki/Class-Diagram), [use case diagram](https://github.com/bounswe/bounswe2022group8/wiki/Use-case-diagram), [sequence diagram](https://github.com/bounswe/bounswe2022group8/wiki/Sequence-Diagrams), scenarios & mockups [1](https://github.com/bounswe/bounswe2022group8/wiki/Class-Diagram), [2](https://github.com/bounswe/bounswe2022group8/wiki/Scenario-2), [3](https://github.com/bounswe/bounswe2022group8/wiki/Scenario-3), and [project plan](https://github.com/bounswe/bounswe2022group8/wiki/CmpE-451-Project-Plan) to the corresponding markdown file in [feature/MIL](https://github.com/bounswe/bounswe2022group8/tree/feature/MIL) branch.

### To Do

- [x] Create a folder named ```CMPE451_Customer_Presentation_Milestone_2``` inside `deliverables`  folder in our repository.
- [x] Deploy the application @ooodogodogodogo 
- [x] Create a pre-release version of our software that marks this version @KarahanS 
>Release Name: 0.2.0-alpha (pre-release option)
Release Description: Brief description w/r to your requirements
Tag name: customer-presentation-2
- [x] All instructions for building must be provided (with docker).
- [ ] The following deliverables must be compiled into a single report. We will be providing the hyperlinks:
   - [x] Software Requirements Specification @mumcusena 
   - [x] Class Diagram  @KarahanS 
   - [ ] Sequence Diagram  @mumcusena 
   - [ ] Use Case Diagram  @mumcusena 
   - [x] Project Plan @kostanya 
   - [x] Individual Contribution Reports
- [x] Customer Milestone 2 Group Review must be completed:
   - [x] Executive Summary @BElifb 
   - [x] Status of Deliverables @MustafaEmreErengul 
   - [x] UI Interface Web @sinemKocoglu   
   - [x] UI Interface Mobil @ooodogodogodogo 
   - [x] Annotations @kostanya 
   - [x] W3C Standards @kostanya and @mustafa-cihan 
- [x] Each member should add a subsection under the `Individual reports` section. These sections should be sorted alphabetically according to the surnames of team members. Please read this part in detail to what to put in this part.

### Deadline

6.12.2022 - 23:55

### Additional Information

We have already made the task distributions covering the majority of the tasks listed above. Don't forget to open the related sub-issue and reference this issue.

### Reviewers

Everyone.

**Comment by KarahanS** [comment]
I'll update the deadline and the list of the deliverables if necessary, when the specification is released.

**Comment by KarahanS** [comment]
Deadline has passed, no further action is taken.
