### ISSUE TITLE
MOB-21: Bug fixes after Milestone 2

### ISSUE THREAD

**Issue by ooodogodogodogo** [bounswe/bounswe2022group8#379]
### What's up?

There were some bugs and minor API changes after Milestone 2 that effects our mobile app. Those issues should be solved in the first place.

### To Do

- [x] Photos have to be compressed before uploading.

- [x] Tokens should be reset after logout.

- [x] Dynamic number of likes.

- [x] Type attribute should be removed from Art Item Class.  

### Deadline

24.12.2022 @ 15.30

### Reviewers

@mustafa-cihan @MustafaEmreErengul @mete

**Comment by mustafa-cihan** [comment]
Everything is fine. Thanks!
