### ISSUE TITLE
MIL-23: Milestone 3 Deliverables

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#418]
### What's up?

All Milestone 3 Deliverables must be completed until 02.01.2023 - 23:55. We should add the hyperlinks of [requirements](https://github.com/bounswe/bounswe2022group8/wiki/Requirements), [class diagram](https://github.com/bounswe/bounswe2022group8/wiki/Class-Diagram), [use case diagram](https://github.com/bounswe/bounswe2022group8/wiki/Use-case-diagram), [sequence diagram](https://github.com/bounswe/bounswe2022group8/wiki/Sequence-Diagrams), scenarios & mockups [1](https://github.com/bounswe/bounswe2022group8/wiki/Class-Diagram), [2](https://github.com/bounswe/bounswe2022group8/wiki/Scenario-2), [3](https://github.com/bounswe/bounswe2022group8/wiki/Scenario-3), and [project plan](https://github.com/bounswe/bounswe2022group8/wiki/CmpE-451-Project-Plan) to the corresponding markdown file in the _feature/MIL_ branch.

### To Do

- [x] Create a folder named ```CMPE451_Customer_Presentation_Milestone_3``` inside `deliverables`  folder in our repository.
- [x] Deploy the application @ooodogodogodogo 
- [x] Create the final release version of our software that marks this version @KarahanS 
>Release Name: 0.3.0-alpha (final release)
Release Description: Brief description w/r to your requirements
Tag name: customer-presentation-3
- [x] All instructions for building must be provided (with docker).
- [x] Executive Summary is to be completed:
   - [x] Project status summary: @serdarakol 
   - [x] Explain the status of the deliverables:  @ooodogodogodogo 
   - [x] Final release notes: @ooodogodogodogo 
   - [x] Describe any changes your team has made or planned based on previous milestones to
improve development process, explain how those changes will impact your process: @mumcusena 
   - [x] Lessons learned from the final milestone demo: @MustafaEmreErengul 
   - [x] What could have been done to finalize the project: @BElifb 
- [ ] Progress based on the teamwork:
   - [x] Status of requirements (classification as _not started_, _in progress_, _completed_): @BElifb 
   - [x] API Endpoints: @KarahanS 
   - [x] User Interface/User Experience: @mustafa-cihan (mobile)  @sinemKocoglu (frontend)
   - [x] Status of the annotations: @mustafa-cihan (mobile)   @sinemKocoglu (frontend)   @KarahanS (backend)
   - [x] Standards:  @KarahanS (Annotations)   @kostanya (Rest of the standards)
   - [x] A comprehensive scenario to cover all the features: @serdarakol  
   > Provide a scenario that encompasses all core functionalities of your project.
Describe in detail the work that has been completed related to the features
necessary to realize this scenario using your application.
   - [ ] Project artifacts:
      - [x] System Manual: @ooodogodogodogo (mobile)   @kostanya (frontend)   @mumcusena (backend)
      - [x] User Manual: @serdarakol 
      - [x] Software Requirements Specification update: @BElifb 
      - [ ] User Scenarios:
         - [x] Art Follower (mobile): @MustafaEmreErengul  (352 and 451 versions will be separated)
         - [x] Artist: @sinemKocoglu 
         - [ ] Collaboration: @kostanya 
       - [x] Project plan: @kostanya 
       - [x] Class diagram: @KarahanS 
       - [ ] Sequence diagram: **Individual** (Everyone will be updating their own sequence diagrams)
       - [x] Use case diagram: @BElifb 
       - [x] Unit tests: **Individual**
    - [x] Our application **Must include database content with at least 100 realistic posts**. Everyone is responsible for creating at least 10 art items/online exhibitions.
- [x] Individual Milestone Reports

### Deadline

02.01.2023 @23.59

### Reviewers

Issue will be closed by the deadline.

**Comment by KarahanS** [comment]
Created a [PR](https://github.com/bounswe/bounswe2022group8/pull/420) to add my summary of work, individual report, status of annotations with respect to backend and annotation related standards.

**Comment by KarahanS** [comment]
Deadline has passed, no further action is required.
