### ISSUE TITLE
Milestone I Report

### ISSUE THREAD

**Issue by KarahanS** [bounswe/bounswe2022group8#73]
**To Do**: As discussed in [Meeting-10](https://github.com/bounswe/bounswe2022group8/wiki/Week6---Meeting-%2310-(06.04.2022)-(PS)), it's time to prepare our first milestone report that gathers the major deliverables related to the requirements, design and plan of our project.
According to our meeting, task allocation is as follows:

- [x] Executive Summary (Project Description and Project Status): @serdarakol 
- [x] List and Status of Deliverables & Evaluation of the status of deliverables: @KarahanS 
- [x] A summary of work done by each member: **everyone** (refer to related [wikipage](https://github.com/bounswe/bounswe2022group8/wiki/Work-Summary-by-Each-Member))
- [x] Evaluation of tools and processes that you have used to manage your team project: @kostanya 
- [x] RAM (responsibility assignment matrix): @simsekhebun, @ooodogodogodogo, @serdarakol, @mumcusena 
- [x] Project Plan: @sinemKocoglu, @kostanya, @KarahanS, @BElifb 
- [x] Combining deliverables (project repository, requirements, software design documents, project plan, RAM, communication plan etc.): @mustafa-cihan 

We will be working in Google Docs to prepare the necessary items. Refer to our Discord channel for the link.
Please refer to this issue in the related sub-issues.

Deadline:  15.04.2022 @19.00

**Comment by KarahanS** [comment]
Milestone I report can be found [here](https://github.com/bounswe/bounswe2022group8/wiki/Milestone-1-Report).
